#pragma once
#include <iostream>
#include <vector>

enum Girl_ID
{
    Cassie = 0,
    Mio,
    Quill,
    Elle,
    Nutaku,
    Iro,
    Bonnnibel,
    Ayano,
    Fumi,
    Bearverly,
    Nina,
    Alpha,
    Pamu,
    Luna,
    Eva,
    Karma,
    Sutra,
    DarkOne,
    Qpernikiss,
    Darya,
    Jelle,
    Quillzone,
    Bonchovy,
    Spectrum,
    Charlotte,
    Odango,
    Shibuki,
    Sirina,
    Catara,
    Vellatrix,
    Peanut,
    Roxxy,
    Tessa,
    Claudia,
    Rosa,
    Juliet,
    Wendy,
    Ruri,
    Generica,
    Suzu,
    Lustat,
    Sawyer,
    Explora,
    Esper,
    Renee,
    Mallory,
    Lake = 46,
    MAX = 46
};

struct Girl
{
    std::string name;
    int id;
};

inline std::vector<Girl> Girls
{
    {"Cassie", Girl_ID::Cassie}, // 0
    {"Mio", Girl_ID::Mio},
    {"Quill", Girl_ID::Quill},
    {"Elle", Girl_ID::Elle},
    {"Nutaku", Girl_ID::Nutaku},
    {"Iro", Girl_ID::Iro},
    {"Bonnnibel", Girl_ID::Bonnnibel},
    {"Ayano", Girl_ID::Ayano},
    {"Fumi", Girl_ID::Fumi},
    {"Bearverly", Girl_ID::Bearverly},
    {"Nina", Girl_ID::Nina},
    {"Alpha", Girl_ID::Alpha},
    {"Pamu", Girl_ID::Pamu},
    {"Luna", Girl_ID::Luna},
    {"Eva", Girl_ID::Eva},
    {"Karma", Girl_ID::Karma},
    {"Sutra", Girl_ID::Sutra},
    {"Dark One", Girl_ID::DarkOne},
    {"Qpernikiss", Girl_ID::Qpernikiss},
    {"Darya", Girl_ID::Darya},
    {"Jelle", Girl_ID::Jelle},
    {"Quillizone", Girl_ID::Quillzone},
    {"Bonchovy", Girl_ID::Bonchovy},
    {"Spectrum", Girl_ID::Spectrum},
    {"Charlotte", Girl_ID::Charlotte},
    {"Odango", Girl_ID::Odango},
    {"Shibuki", Girl_ID::Shibuki},
    {"Catara", Girl_ID::Catara},
    {"Vellatrix", Girl_ID::Vellatrix},
    {"Peanut", Girl_ID::Peanut},
    {"Roxxy", Girl_ID::Roxxy},
    {"Tessa", Girl_ID::Tessa},
    {"Claudia", Girl_ID::Claudia},
    {"Rosa", Girl_ID::Rosa},
    {"Juliet", Girl_ID::Juliet},
    {"Wendy", Girl_ID::Wendy},
    {"Ruri", Girl_ID::Ruri},
    {"Generica", Girl_ID::Generica},
    {"Suzu", Girl_ID::Suzu},
    {"Lustat", Girl_ID::Lustat},
    {"Sawyer", Girl_ID::Sawyer},
    {"Explora", Girl_ID::Explora},
    {"Esper", Girl_ID::Esper},
    {"Renee", Girl_ID::Renee},
    {"Mallory", Girl_ID::Mallory},
    {"Lake", Girl_ID::Lake} // 46
};
