name: Build Visual Studio Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore "OmegaWare Framework/OmegaWare Framework.sln"

    - name: Build Solution
      run: msbuild "OmegaWare Framework/OmegaWare Framework.sln" /m /p:Configuration=${{ matrix.configuration }}

    - name: Verify Artifacts
      run: dir "Crush-Crush-Cheat/OmegaWare Framework/Build/Win32/${{ matrix.configuration }}"
