name: Build Visual Studio C++ Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSBuild 17.11.9
      run: |
        choco install visualstudio2022buildtools --version=17.11.9 --no-progress --yes
        choco install visualstudio2022-workload-vctools --version=17.11.9 --no-progress --yes
        echo "##[add-path]C:\\Program Files\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin" >> $GITHUB_ENV

    - name: Set Environment Variables
      run: |
        echo "SOLUTION_PATH=OmegaWare Framework/OmegaWare Framework.sln" >> $GITHUB_ENV
        echo "BUILD_OUTPUT_PATH=OmegaWare Framework/Build/Win32/${{ matrix.configuration }}" >> $GITHUB_ENV

    - name: Restore NuGet packages
      run: nuget restore "${{ env.SOLUTION_PATH }}"

    - name: Build Solution
      run: msbuild "${{ env.SOLUTION_PATH }}" /m /p:Configuration=${{ matrix.configuration }}

    - name: Verify Artifacts
      run: dir "${{ env.BUILD_OUTPUT_PATH }}"
